version: "3"

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf
    ports:
      - "2358:2358"
    depends_on:
      - redis
      - db

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf
    depends_on:
      - redis
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: judge0
      POSTGRES_PASSWORD: judge0
      POSTGRES_DB: judge0
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  db_data: